apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
      version: green
  template:
    metadata:
      labels:
        app: sample-app
        version: green
    spec:
      containers:
      - name: sample-app
        image: darshants/sample-app:latest
        ports:
        - containerPort: 80
